[package]
name = "amc-auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Authentication module for AMC Launcher (Microsoft OAuth2, WetID, Offline)"

[dependencies]
amc-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
md-5 = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
