[package]
name = "amc-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Aleph Studio GUI renderer, widgets, pages and themes for AMC Launcher"

[dependencies]
amc-core = { workspace = true }
amc-auth = { workspace = true }
amc-downloader = { workspace = true }
amc-minecraft = { workspace = true }
amc-mods = { workspace = true }

egui = { workspace = true }
eframe = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
image = { workspace = true }
parking_lot = { workspace = true }
open = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rfd = { workspace = true }
